### ISSUE TITLE
Support Redis Sentinel on Svix Server

### ISSUE THREAD

**Issue by tu-pm** [svix/svix-webhooks#1293]
### Motivation

Redis Sentinel is a common HA practice for a small production deployment of Redis, since it requires much less physical resources to ensure high availability compare to Redis Cluster. It'd be nice if Svix supports Sentinel as well.

**Comment by tasn** [comment]
@svix-james, what do you think?

**Comment by svix-james** [comment]
I know next to nothing about sentinel so am not positive offhand, but I'm sure it's doable. The library supports sentinel.

**Comment by andrewmatthews** [comment]
Hi guys, I'm wondering if there is any more information on this? If the library supports Sentinel, perhaps it is simply a matter of the correct configuration. This is how other Redis libraries work.

**Comment by sanjaywinjit** [comment]
How about support for AWS ElasticCache ?

**Comment by svix-james** [comment]
@andrewmatthews We now have support for Redis Sentinel in `main`. It should be available in our next release. In order to try it, you'll need to at a minimum add these configuration parameters.

`redis_dsn` -- should point to a sentinel server
`sentinel_service_name` -- the name of the sentinel service

I don't recommend this for production workloads at this point without a good amount of testing. It has been lightly tested on our end, and there are some upstream optimizations that need to be made in the redis library. I will try to work on that at some point. 

Fixed by https://github.com/svix/svix-webhooks/pull/1472
