### ISSUE TITLE
Use clippy::pedantic

### ISSUE THREAD

**Issue by SuperFluffy** [svix/svix-webhooks#279]
## Feature Request

Run clippy in pedantic mode, `-W clippy::pedantic`.

### Motivation

Right now clippy is run in standard mode, which is quite lenient and does not catch a lot of common nits. `clippy::pedantic` very rarely has false positives, but from experience it catches style mistakes that even relatively experienced rust devs make (looking at myself here....). Its suggestions will help very much with long term maintenance and enforce a stricter programming style. Especially when on-boarding new devs without Rust experience pedantic clippy acts as a teacher. :-)

This should be done ASAP while the code base is relatively small (at the time of writing, clippy raises 81 warnings). Adding this later on will be painful.

### Proposal

Require `-W clippy::pedantic` in CI. This will require a bigger PR to implement all clippy suggestions so that CI passes.

### Alternatives

+ Punt it until later (not a good idea; will be painful);
+ Ignore it (don't see a good reason to).

**Comment by tasn** [comment]
Great suggestion, thanks a lot!

CC @svix-daniel who also brought it up yesterday. :)

**Comment by svix-jplatte** [comment]
We had a few PRs for this that were all closed because the benefits of the changes were not very clear.
I've tried `clippy::pedantic` a few times in other projects and also never found it to be very useful.

We are running some non-default lints now (for example, [here](https://github.com/svix/svix-webhooks/commit/0a281322e13b7cb260c089c594cf5d8e9a795e45) we enabled `rust_2018_idioms`, a rustc lint group), but `clippy::pedantic` seems to large and controversial of a lint group.
