### ISSUE TITLE
Consider switching base docker image to debian-slim

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#302]
See comment on HN: https://news.ycombinator.com/item?id=30635160

Maybe it doesn't affect us, if we are using a rust implementation of DNS, but I'm not sure. Need to check what `rust-tls` does. Though maybe it's a good idea to switch.

**Comment by CGreenburg** [comment]
Another option could be to use https://github.com/GoogleContainerTools/distroless (they have a rust example).

If distroless is used, it nullifies the `wait-for` script since it uses `nc` and `wget` which likely aren't available in the image. But that could also be an opportunity to bake the waiting and retrying connections to postgres/redis into the server itself during initialization (if it doesn't already).

**Comment by tasn** [comment]
Yeah, I really want to add "wait-for", and to be honest, reconnecting into the Rust binary itself, so it's probably a good idea.
