### ISSUE TITLE
Remove Ruby gem hard-dependency on typhoeus

### ISSUE THREAD

**Issue by bf4** [svix/svix-webhooks#453]
### Motivation

I'd be happy to use this gem to verify the webhook code, but I don't want to install typhoeus, which isn't needed for it. So, until it's removed, I'll probably just write the HMAC etc code myself.

### Proposal

MVP: make typhoeus a soft requirement for use in the api client, but not for installation. 

### Alternatives

Remove typhoeus altogether.

**Comment by tasn** [comment]
I'm no Ruby expert, how can we make it a soft dep?

In the meanwhile feel free to copy the HMAC code, it's licensed as MIT.

**Comment by bf4** [comment]
99% documentation e.g. see how Rails makes bcrypt a soft dep

https://github.com/rails/rails/blob/98b2e8a4968827beb6460174c3caf13a33487921/activemodel/lib/active_model/secure_password.rb#L42-L89


```ruby
      # To use +has_secure_password+, add bcrypt (~> 3.1.7) to your Gemfile:
      #
      #   gem 'bcrypt', '~> 3.1.7'
      def has_secure_password(attribute = :password, validations: true)
        # Load bcrypt gem only when has_secure_password is used.
        # This is to avoid ActiveModel (and by extension the entire framework)
        # being dependent on a binary library.
        begin
          require "bcrypt"
        rescue LoadError
          $stderr.puts "You don't have bcrypt installed in your application. Please add it to your Gemfile and run bundle install."
          raise
        end
        # etc.
```

**Comment by tasn** [comment]
Gotcha. I'm more inclined to just drop typhoeus altogether. Need to figure out whether this is feasible.

**Comment by bf4** [comment]
Yeah, if you want to support an adapter for other http clients, and want to use a gem for that, faraday is pretty standard. Otherwise, just need a consistent interface in the code

```ruby
      request = Typhoeus::Request.new(url, req_opts)
      download_file(request) if opts[:return_type] == 'File'
      request
```

**Comment by tasn** [comment]
I think the problem is that we get it from the open API generator, so we don't have full control over getting rid of it.

**Comment by swarna1101** [comment]
One way to achieve this would be to make typhoeus a "soft requirement" for the gem, which means that it is not necessary to install typhoeus in order to use the gem, but it may be used as an optional dependency if it is available. This can be done by modifying the gem's dependencies in its codebase to use a "soft requirement" syntax, such as `gem 'typhoeus', '~> 1.3', require: false`.

Another alternative would be to remove typhoeus as a requirement altogether, either by replacing it with another library or by removing the functionality that relies on it. This would allow the gem to be used without requiring the installation of any additional dependencies.

Ultimately, the approach that is taken will depend on the needs of the gem and its users, as well as the feasibility of implementing the requested changes.

**Comment by jjb** [comment]
not sure why people piled onto @swarna1101's suggestion, it's a fine suggestion and afaict the same as what OP is suggesting

Here's a PR to implement that: https://github.com/svix/svix-webhooks/pull/1486

I don't know much about openapi generator or moustache - can i edit that template?

**Comment by jjb** [comment]
@tasn can you approve CI on my PR? 🙇
