### ISSUE TITLE
Consider IETF HTTP Message Signatures draft

### ISSUE THREAD

**Issue by alexrejto** [svix/svix-webhooks#501]
## Feature Request
Move svix from using HMAC endpoint signing to the [IETF HTTP Message Signatures](https://datatracker.ietf.org/doc/draft-ietf-httpbis-message-signatures/) draft. The IETF draft decreases the number of secrets in a system which is very appealing. Would svix consider implementing this; even on a long-term time frame?

An example implementation is [here](https://github.com/pyauth/http-message-signatures) in Python.

**Comment by tasn** [comment]
Are you referring to its (optional) use of asymmetric signatures compared to the symmetric signatures (HMAC) in Svix? Or are there other properties of this RFC that you find appealing?

Because if it's just the asymmetric signatures (so you can reduce the number of secrets in the system), this is definitely something that we can do and have been considering. There are a few downsides to going with asymmetric signatures (which is also why we don't use them by default), though we can definitely make it an option.

Some of the downsides:
1. Performance. I just ran a benchmark, and my (beefy) laptop can do:
    1. HMAC: 1,500,000m sign and 1,500,000 verify per second. 
    2. RSA: 2,000 sign and 50,000 verify per second.
    3. EdDSA (Ed25519): 30,095 sign and 8,904 verify per second.
    4. As you can see, if you want asymmetric you'd want Ed25519, though even with this performance is not great. These numbers may look high, but they'll be much lower on a small server, and this server will want to do more things than just calculating signatures. This is a burden for both the sender and the receiver.
2. Complexity for the customer, and availability of libraries. HMAC-SHA256 is ubiquitous, and has good implementations for many languages. RSA has a lot of buggy implementations and not always available, and EdDSA is newer and doesn't have many implementations. So you are putting a large burden on your customer to be able to source an implementation, make sure it's good, and use it. It's maybe less of a concern with Svix because we already write libraries for you in every environment, but we'll need to source good implementations.
3. More pressure on the PRNG (and needing to get good source of random values) - probably not a massive concern, but the server will also need a lot of (quality) random values to do a lot of signatures. This is more tricky than you may think, and it could lead to a failure here, and potentially even a key disclosure.
4. Because there are less keys, key rotation becomes a global, rather than a local problem. As in, if you feel like your key was compromised for whatever reason, all of your customers need to update their verification code to use the new key.

There are obviously upsides to having just one key, especially since it doesn't have to be secret in the asymmetric case.


Sorry for the wall of text, I just wanted to share some context. Looking forward to hearing your thoughts, and whether you're interested in this standard as a whole, or just the asymmetric key aspect of it.

**Comment by tasn** [comment]
We opened #525 which should fix it.
