### ISSUE TITLE
Support upserting entities on PUT requests

### ISSUE THREAD

**Issue by BarakW** [svix/svix-webhooks#603]
## Feature Request
It seems that today PUT requests don't create resources that don't already exist (unless they were previously deleted).

Could we support creating resources on all PUT requests?

### Motivation
The current behavior is a bit out of line with standard rest behavior that expects PUT requests to create a resource if it doesn't already exist https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT.

### Proposal

Enable upserting from PUT endpoints.

The resources that would see the most upserting are probably:
1. Applications
2. Endpoints
3. Event types

### Alternatives

It's possible to get the same behavior today with try/catch'ing a POST and PUT, but this is extra boilerplate that doesn't offer any distinct advantage or flexibility for many use cases.

**Comment by svix-dylan** [comment]
Hey @BarakW, forgot to comment but this is a great suggestion and I started taking a look at it earlier today. We'll ping you on this thread when we merge a PR for this!

**Comment by svix-dylan** [comment]
Hi @BarakW happy to inform you a PR resolving this has been merged! On main, PUT method requests to Application, Endpoint, and Event Type will now create an entity and return 201 if a record matching the provided ID doesn't exist -- otherwise, the existing entity will be updated and the server will return 200.
