### ISSUE TITLE
Server: change use of Axum `Extension` with `State`

### ISSUE THREAD

**Issue by tasn** [svix/svix-webhooks#726]
We probably want to just pass this state to the worker too, and have a global state of connection pools, etc.

**Comment by swarna1101** [comment]
The purpose of this change is not clear from the information provided. However, it seems that the intention is to pass this state object to a worker and use it to manage connection pools and other resources.

To implement this change, you will need to modify the server code to pass the state object to the worker and use it to manage resources instead of the Axum Extension. You will also need to ensure that the worker has access to the state object and knows how to use it to manage resources.

It's worth noting that this is just one possible approach to the problem, and there may be other solutions that would be more appropriate depending on the specific needs of the project. It's always a good idea to carefully consider the implications of any code changes before implementing them.
