### ISSUE TITLE
Allow signature validation without timestamp tolerance enforcement

### ISSUE THREAD

**Issue by svix-frank** [svix/svix-webhooks#93]
Should keep it enabled by default, but we might want to allow custom tolerances or allow to disable the tolerance enforcement altogether.

Can be useful if you want to verify old payloads or if you have a bad clock.

**Comment by masahiro-yamamoto-rc** [comment]
@svix-frank 
Would you let me know why this issue was closed, please?

We are in a situation where we need to use a custom tolerance.
We are going to create a subclass of `__verify_timestamp`, but wondering why such a simple method is prefixed with double underscore.
https://github.com/svix/svix-webhooks/blob/03ab8b993df6094329ac47f7e2f130fd53e8fc24/python/svix/webhooks.py#L67-L79

**Comment by dimaqq** [comment]
Asking for the same tweak but for a different reason than OP: sometimes, things go bad in production and webhooks need to be retried for business reasons.

Ref: https://news.ycombinator.com/item?id=27823109

**Comment by tasn** [comment]
I reopened it. No idea why it was closed, but at the very least it's useful for tests (if not a variety of other use-cases too).

> Asking for the same tweak but for a different reason than OP: sometimes, things go bad in production and webhooks need to be retried for business reasons.

You should generate a new signature when you retry (Svix already does it).

**Comment by svix-jplatte** [comment]
There's a function `VerifyIgnoringTimestamp` for this nowadays. Please let us know if we closed this in error.

**Comment by seanarnold** [comment]
@svix-jplatte it appears `VerifyIgnoringTimestamp` is only in the Go library, is that intended?

**Comment by ogenodisho** [comment]
Hi @svix-jplatte , I raised a PR to address this issue: #2055
